version: '3'

networks:
  matecat-network:
    driver: bridge

services:
  filters:
    build: ./MateCatFilters/
    ports:
      - 8732:8732
    networks:
      - matecat-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - matecat-network

  amq:
    build: ./AMQ/
    ports:
      - 61613:61613
      - 8161:8161
    networks:
      - matecat-network
       
  mysql:
    build: ./MySQL/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - matecat-network

  matecat:
    build: ./MateCatApache/
    ports:
      - 80:80
    environment: 
      - MATECAT_HOST=http://localhost
      - MATECAT_COOKIE_DOMAIN=localhost
      - SMTP_USERNAME=info@example.com
      - SMTP_SENDER=info@example.com
      - SMTP_PORT=587
      - SMTP_PASSWORD=example
      - SMTP_HOST=some.smtp.host.com
      - TM_NAME=NEC-TM
      - TM_ENDPOINT=http://nectm-connector:5000
    networks:
      - matecat-network
    depends_on:
      - mysql
      - redis
      - amq
      - filters
      - nectm-connector

  nectm-connector:
    image: docker.crosslang.com/nectm-connector
    command: flask run
    ports:
      - "5000:5000"
    depends_on: 
      - nectm
    networks:
      - matecat-network
    
  nectm:
    image: nectm/activatm
    ports:
      - "27979:7979"
      - "27878:7878"
      - "19200:9200"
    volumes: 
      - ./elasticsearch_data:/elasticsearch_data
    networks:
      - matecat-network
