version: '2'

networks:
  matecat-network:
    driver: bridge

services:
  filters:
    build: ./MateCatFilters/
    container_name: docker_matecat_filter
    expose:
      - 8732
    networks:
       - matecat-network

  redis:
    image: redis
    expose:
      - 6379
    networks:
       - matecat-network

  amq:
    build: ./AMQ/
    expose:
      - 61613
      - 61616
    ports:
      - 8161:8161
    networks:
       - matecat-network
       
  mysql:
    build: ./MySQL/
    container_name: docker_mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
    expose:
     - 3306
    networks:
       - matecat-network

  matecat:
    build: ./MateCatApache/
    container_name: docker_matecat
    ports:
      - 80:80
    networks:
       - matecat-network
    links:
      - mysql
      - redis
      - amq
      - filters
      - mouse
      - parrot

  mouse:
    image: docker.crosslang.com/mouse
    ports:
     - 8080:8080
    environment:
     - MOUSE_PROTOCOL=http
     - MOUSE_HOSTNAME=localhost
     - MOUSE_PORT=8080
    networks:
     - matecat-network

  parrot:
    image: docker.crosslang.com/parrot
    ports:
     - 8090:8080
    networks:
     - matecat-network

  # tcpdump:
  #   image: kaazing/tcpdump
  #   network_mode: "host"
  #   volumes:
  #     - ./tcpdump:/tcpdump
