version: '2'

networks:
  matecat-network:
    driver: bridge

services:
  filters:
    build: ./MateCatFilters/
    container_name: docker_matecat_filter
    ports:
      - 8732:8732
    networks:
       - matecat-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
       - matecat-network

  amq:
    image: webcenter/activemq:latest
    ports:
      - 61613:61613
      - 61616:61616
      - 8161:8161

  mysql:
    build: ./MySQL/
    container_name: docker_mysql
    ports:
     - 3306:3306
    networks:
       - matecat-network

  matecat:
    build: ./MateCatApache/
    container_name: docker_matecat
    volumes:
      - ~/matecat:/var/www/matecat:rw
    ports:
      - 80:80
      - 7788:7788
      - 22
    networks:
       - matecat-network
    links:
      - mysql
      - redis
      - amq
      - filters
