FROM ubuntu:latest

#RUN dpkg-divert --local --rename --add /sbin/initctl
#RUN ln -snvf /bin/true /sbin/initctl
#ENV DEBIAN_FRONTEND noninteractive

COPY mysql_pubkey.asc /etc/mysql/mysql_pubkey.asc
RUN apt-get -y update
RUN apt-get install -y gnupg
RUN apt-key add /etc/mysql/mysql_pubkey.asc
#RUN echo "deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7" >> /etc/apt/sources.list.d/mysql.list
RUN echo "deb http://repo.mysql.com/apt/ubuntu/ trusty connector-python-2.0" >> /etc/apt/sources.list.d/mysql.list
RUN apt-get update
RUN apt-get install -y mariadb-server mariadb-client

RUN mkdir -p /var/run/mysqld
RUN touch /var/run/mysqld/mysqld.sock
RUN touch /var/run/mysqld/mysqld.pid
RUN chown -R mysql:mysql /var/run/mysqld/*
RUN chmod 777 /var/run/mysqld/mysqld.sock
RUN chmod 644 /var/run/mysqld/mysqld.pid

COPY run.sh /tmp/run.sh
RUN chmod +x /tmp/run.sh

COPY my.cnf /etc/mysql/my.cnf
RUN chown mysql:mysql /etc/mysql/my.cnf
RUN chmod 660 /etc/mysql/my.cnf

ENV MYSQL_PASS "admin"
COPY create_mysql_admin_user.sh /tmp/create_mysql_admin_user.sh
RUN chmod +x /tmp/create_mysql_admin_user.sh

CMD ["/tmp/run.sh"]

